apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bmi-apps-matrix
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/bernardolsp/microservicos-argocd-treinamento.git
          revision: HEAD
          directories:
          - path: helm/*
          pathParamPrefix: app
      - git:
          repoURL: https://github.com/bernardolsp/microservicos-argocd-treinamento.git
          revision: HEAD
          files:
          - path: "helm/config.json"
          pathParamPrefix: config
  template:
    metadata:
      name: '{{.cluster_name}}-{{.app.path.basename}}'
    spec:
      project: "default"
      sources:
        - repoURL: https://github.com/bernardolsp/microservicos-argocd-treinamento.git
          targetRevision: HEAD
          path: '{{.app.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.cluster_name}}-{{.app.path.basename}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true

