apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bmi-service
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/bernardolsp/microservicos-argocd-treinamento.git
      revision: HEAD
      files:
      - path: "helm/config.json"
  template:
    metadata:
      name: '{{.cluster_name}}-bmi-service'
    spec:
      project: default
      source:
        repoURL: https://github.com/bernardolsp/microservicos-argocd-treinamento.git
        targetRevision: HEAD
        path: "helm/bmi-service"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.cluster_name}}-bmi-service'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true