apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bmi-service
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          environment: "secondary"
  template:
    metadata:
      name: '{{.name}}-bmi-service'
    spec:
      project: default
      source:
        repoURL: https://github.com/bernardolsp/microservicos-argocd-treinamento.git
        targetRevision: HEAD
        path: helm/bmi-service
      destination:
        server: '{{.server}}' 
        namespace: bmi-service
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
